apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  interval: 1m
  chart:
    spec:
      chart: karpenter
      version: v0.16.2
      sourceRef:
        kind: HelmRepository
        name: karpenter
        namespace: karpenter
      interval: 1m
  values:
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::330700974597:role/joinnis-karpenter-demo-karpenter
    clusterName: joinnis-karpenter-demo
    clusterEndpoint: https://2B3A0347E5BF8D9935288F4311843065.gr7.us-west-2.eks.amazonaws.com
    aws:
      defaultInstanceProfile: KarpenterNodeInstanceProfile-joinnis-karpenter-demo