apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: extended-karpenter-role
  namespace: karpenter
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch", "update"]
  resourceNames:
    - karpenter