apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extended-karpenter-binding
  namespace: karpenter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extended-karpenter-role
subjects:
- kind: ServiceAccount
  name: karpenter
  namespace: karpenter