---
# Source: karpenter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter
  namespace: default
  labels:
    helm.sh/chart: karpenter-0.16.2
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/version: "0.16.2"
    app.kubernetes.io/managed-by: Helm